from models.gradient_boosting_regression import GradientBoostingRegression
from models.random_forest_regression import RandomForestRegression
from models.simple_linear_regression import SimpleLinearRegression
from models.support_vector_machine_regression import SupportVectorMachineRegression
from models.support_vector_machine_regression_poly3 import  SupportVectorMachineRegressionPoly3